version: '2.4'
services:
 ptndown-sp-pia:
  build:
    args:
      PIA_USER: ${PIA_USER}
      PIA_PASS: ${PIA_PASS}
      SP_USERAGENT: ${SP_USERAGENT}
    context: .
    dockerfile: Dockerfile
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 77.88.8.1
    - 77.88.8.2
  extra_hosts:
    - 12-kanal.ru:109.194.112.233
    - 360tv.ru:95.213.164.20
    - 47news.ru:77.244.221.63
    - donbasstoday.ru:193.233.15.62
    - www.donnews.ru:185.179.190.159
    - www.europereloaded.com:147.135.97.116
    - fine-news.ru:213.139.208.57
    - mosregtoday.ru:178.154.213.69
    - novorossiia.ru:87.236.16.191
    - pizzahut.ru:185.98.84.80
    - politcentr.ru:87.236.16.126
    - russia-insider.com:158.69.116.70
    - sbarro-pizza.ru:185.165.123.36
    - thesaker.is:23.111.129.34
    - www.voltairenet.org:65.108.13.235
    - wpristav.com:193.109.246.53
  image: fluxstate/ptndown-sp-pia
  ports:
    - "8049/tcp"
  restart: unless-stopped
  sysctls:
    - net.ipv4.tcp_timestamps=0
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.default.disable_ipv6=1
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
